/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false` (hash: 3cb8c156b205500ca9680808bd39bf87)
interface __BaseEnv_Env {
	LINKS_KV: KVNamespace;
	CLICK_QUEUE: Queue;
	SUPABASE_URL: "https://your-project.supabase.co";
	SMART_LINK_CACHE_TTL_SECONDS: "300";
	SUPABASE_SERVICE_ROLE_KEY: string;
	CLICK_HASH_SALT: string;
	LINKS_SYNC_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_URL" | "SMART_LINK_CACHE_TTL_SECONDS" | "SUPABASE_SERVICE_ROLE_KEY" | "CLICK_HASH_SALT" | "LINKS_SYNC_TOKEN">> {}
}
