/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false` (hash: 1470a1c49c37c3102647fa59805940c6)
interface __BaseEnv_Env {
	APP_CONFIG_CACHE: KVNamespace;
	INGEST_METRICS: AnalyticsEngineDataset;
	EVENT_QUEUE: Queue;
	DEAD_LETTER_QUEUE: Queue;
	APP_RATE_LIMIT: RateLimit;
	IP_RATE_LIMIT: RateLimit;
	ABUSE_RATE_LIMIT: RateLimit;
	APP_CONFIG_CACHE_TTL_SECONDS: "60";
	MAX_REQUEST_BYTES: "262144";
	SUPABASE_URL: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_CONFIG_CACHE_TTL_SECONDS" | "MAX_REQUEST_BYTES" | "SUPABASE_URL" | "SUPABASE_SERVICE_ROLE_KEY">> {}
}
